### ISSUE TITLE
can this rep run with source code?

### ISSUE THREAD

**Issue by fooSynaptic** [waldenlqy/SAM#1]
File "./SAM/SAM_codes/sam_model/sparse_attentive_memory_network.py", line 136
    def _create_memory_network_gru(self, long_seq_input_layer, query_layer, key_masks, units=16, mode='stk'):
                                                                                                             ^
IndentationError: unindent does not match any outer indentation level

**Comment by waldenlqy** [comment]
Should be, I directly extracted the methods from our source code. The
indentation might be due to merging with other codes? If there are some
minor problems, maybe just adjust the indentation a little bit. We use
python 3.
